fragment PostParts on Post {
  title
  date
  draft
  body
}

fragment TeamParts on Team {
  published
  name
  position
  bio
  photo
  linkedin_url
  twitter_url
}

fragment PagesParts on Pages {
  published
  page_name
  page_blocks {
    __typename
    ... on PagesPage_blocksBlock_content {
      heading
      body
    }
  }
}
