---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
- type: heading
  label: Blog
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: document
  path: src/data/authors.json
  label: Authors Data
- type: heading
  label: Team
- type: directory
  path: src/people
  label: People
  create: all
  match: "**/*"
- type: heading
  label: Globals
- type: document
  path: src/globals
  label: Footer
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
