---
label: Settings
hide_body: true
display_field: name
fields:
- name: company_name
  type: text
  config:
    required: true
  label: Company name
- name: email
  type: text
  config:
    required: true
  label: Email
- name: footer_text
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Footer text
pages:
- src/globals/settings.json
- src/globals/settings.json
