---
label: Profiles
hide_body: true
display_field: name
fields:
- name: published
  type: boolean
  label: Published
  hidden: false
  default: true
- name: name
  type: text
  config:
    required: true
  label: Name
- name: position
  type: text
  config:
    required: false
  label: Position
- name: bio
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Bio
- name: photo
  type: file
  config:
    maxSize: 64
  label: Photo
- name: linkedin_url
  type: text
  config:
    required: false
  label: LinkedIn URL
- name: twitter_url
  type: text
  config:
    required: false
  label: Twitter URL
pages:
- src/content/profiles/erlich-bachman.md
