---
label: Profiles
hide_body: false
fields:
- name: name
  type: text
  config:
    required: true
  label: Name
- name: bio
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Bio
